server:
  port: 17777
spring:
  application:
    name: drug-server
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drug?useUnicode=true&charcterEncoding=utf8&serverTimezone=Asia/Shanghai
    password: 1234
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
mybatis:
  mapper-locations: classpath:/mappers/*.xml
